# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: slm.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'slm.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\tslm.proto\x12\x03slm\"1\n\x0fGenerateRequest\x12\x0e\n\x06prompt\x18\x01 \x01(\t\x12\x0e\n\x06maxNew\x18\x02 \x01(\x05\" \n\x10GenerateResponse\x12\x0c\n\x04text\x18\x01 \x01(\t2E\n\nSlmService\x12\x37\n\x08generate\x12\x14.slm.GenerateRequest\x1a\x15.slm.GenerateResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'slm_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_GENERATEREQUEST']._serialized_start=18
  _globals['_GENERATEREQUEST']._serialized_end=67
  _globals['_GENERATERESPONSE']._serialized_start=69
  _globals['_GENERATERESPONSE']._serialized_end=101
  _globals['_SLMSERVICE']._serialized_start=103
  _globals['_SLMSERVICE']._serialized_end=172
# @@protoc_insertion_point(module_scope)
