// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: slm.proto

#include "slm.pb.h"
#include "slm.grpc.pb.h"

#include <functional>
#include <grpcpp/support/async_stream.h>
#include <grpcpp/support/async_unary_call.h>
#include <grpcpp/impl/channel_interface.h>
#include <grpcpp/impl/client_unary_call.h>
#include <grpcpp/support/client_callback.h>
#include <grpcpp/support/message_allocator.h>
#include <grpcpp/support/method_handler.h>
#include <grpcpp/impl/rpc_service_method.h>
#include <grpcpp/support/server_callback.h>
#include <grpcpp/impl/server_callback_handlers.h>
#include <grpcpp/server_context.h>
#include <grpcpp/impl/service_type.h>
#include <grpcpp/support/sync_stream.h>
#include <grpcpp/ports_def.inc>
namespace slm {

static const char* SlmService_method_names[] = {
  "/slm.SlmService/generate",
};

std::unique_ptr< SlmService::Stub> SlmService::NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options) {
  (void)options;
  std::unique_ptr< SlmService::Stub> stub(new SlmService::Stub(channel, options));
  return stub;
}

SlmService::Stub::Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options)
  : channel_(channel), rpcmethod_generate_(SlmService_method_names[0], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  {}

::grpc::Status SlmService::Stub::generate(::grpc::ClientContext* context, const ::slm::GenerateRequest& request, ::slm::GenerateResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::slm::GenerateRequest, ::slm::GenerateResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_generate_, context, request, response);
}

void SlmService::Stub::async::generate(::grpc::ClientContext* context, const ::slm::GenerateRequest* request, ::slm::GenerateResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::slm::GenerateRequest, ::slm::GenerateResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_generate_, context, request, response, std::move(f));
}

void SlmService::Stub::async::generate(::grpc::ClientContext* context, const ::slm::GenerateRequest* request, ::slm::GenerateResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_generate_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::slm::GenerateResponse>* SlmService::Stub::PrepareAsyncgenerateRaw(::grpc::ClientContext* context, const ::slm::GenerateRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::slm::GenerateResponse, ::slm::GenerateRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_generate_, context, request);
}

::grpc::ClientAsyncResponseReader< ::slm::GenerateResponse>* SlmService::Stub::AsyncgenerateRaw(::grpc::ClientContext* context, const ::slm::GenerateRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncgenerateRaw(context, request, cq);
  result->StartCall();
  return result;
}

SlmService::Service::Service() {
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      SlmService_method_names[0],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< SlmService::Service, ::slm::GenerateRequest, ::slm::GenerateResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](SlmService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::slm::GenerateRequest* req,
             ::slm::GenerateResponse* resp) {
               return service->generate(ctx, req, resp);
             }, this)));
}

SlmService::Service::~Service() {
}

::grpc::Status SlmService::Service::generate(::grpc::ServerContext* context, const ::slm::GenerateRequest* request, ::slm::GenerateResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}


}  // namespace slm
#include <grpcpp/ports_undef.inc>

