// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: slm.proto
#ifndef GRPC_slm_2eproto__INCLUDED
#define GRPC_slm_2eproto__INCLUDED

#include "slm.pb.h"

#include <functional>
#include <grpcpp/generic/async_generic_service.h>
#include <grpcpp/support/async_stream.h>
#include <grpcpp/support/async_unary_call.h>
#include <grpcpp/support/client_callback.h>
#include <grpcpp/client_context.h>
#include <grpcpp/completion_queue.h>
#include <grpcpp/support/message_allocator.h>
#include <grpcpp/support/method_handler.h>
#include <grpcpp/impl/proto_utils.h>
#include <grpcpp/impl/rpc_method.h>
#include <grpcpp/support/server_callback.h>
#include <grpcpp/impl/server_callback_handlers.h>
#include <grpcpp/server_context.h>
#include <grpcpp/impl/service_type.h>
#include <grpcpp/support/status.h>
#include <grpcpp/support/stub_options.h>
#include <grpcpp/support/sync_stream.h>
#include <grpcpp/ports_def.inc>

namespace slm {

class SlmService final {
 public:
  static constexpr char const* service_full_name() {
    return "slm.SlmService";
  }
  class StubInterface {
   public:
    virtual ~StubInterface() {}
    virtual ::grpc::Status generate(::grpc::ClientContext* context, const ::slm::GenerateRequest& request, ::slm::GenerateResponse* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::slm::GenerateResponse>> Asyncgenerate(::grpc::ClientContext* context, const ::slm::GenerateRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::slm::GenerateResponse>>(AsyncgenerateRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::slm::GenerateResponse>> PrepareAsyncgenerate(::grpc::ClientContext* context, const ::slm::GenerateRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::slm::GenerateResponse>>(PrepareAsyncgenerateRaw(context, request, cq));
    }
    class async_interface {
     public:
      virtual ~async_interface() {}
      virtual void generate(::grpc::ClientContext* context, const ::slm::GenerateRequest* request, ::slm::GenerateResponse* response, std::function<void(::grpc::Status)>) = 0;
      virtual void generate(::grpc::ClientContext* context, const ::slm::GenerateRequest* request, ::slm::GenerateResponse* response, ::grpc::ClientUnaryReactor* reactor) = 0;
    };
    typedef class async_interface experimental_async_interface;
    virtual class async_interface* async() { return nullptr; }
    class async_interface* experimental_async() { return async(); }
   private:
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::slm::GenerateResponse>* AsyncgenerateRaw(::grpc::ClientContext* context, const ::slm::GenerateRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::slm::GenerateResponse>* PrepareAsyncgenerateRaw(::grpc::ClientContext* context, const ::slm::GenerateRequest& request, ::grpc::CompletionQueue* cq) = 0;
  };
  class Stub final : public StubInterface {
   public:
    Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());
    ::grpc::Status generate(::grpc::ClientContext* context, const ::slm::GenerateRequest& request, ::slm::GenerateResponse* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::slm::GenerateResponse>> Asyncgenerate(::grpc::ClientContext* context, const ::slm::GenerateRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::slm::GenerateResponse>>(AsyncgenerateRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::slm::GenerateResponse>> PrepareAsyncgenerate(::grpc::ClientContext* context, const ::slm::GenerateRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::slm::GenerateResponse>>(PrepareAsyncgenerateRaw(context, request, cq));
    }
    class async final :
      public StubInterface::async_interface {
     public:
      void generate(::grpc::ClientContext* context, const ::slm::GenerateRequest* request, ::slm::GenerateResponse* response, std::function<void(::grpc::Status)>) override;
      void generate(::grpc::ClientContext* context, const ::slm::GenerateRequest* request, ::slm::GenerateResponse* response, ::grpc::ClientUnaryReactor* reactor) override;
     private:
      friend class Stub;
      explicit async(Stub* stub): stub_(stub) { }
      Stub* stub() { return stub_; }
      Stub* stub_;
    };
    class async* async() override { return &async_stub_; }

   private:
    std::shared_ptr< ::grpc::ChannelInterface> channel_;
    class async async_stub_{this};
    ::grpc::ClientAsyncResponseReader< ::slm::GenerateResponse>* AsyncgenerateRaw(::grpc::ClientContext* context, const ::slm::GenerateRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::slm::GenerateResponse>* PrepareAsyncgenerateRaw(::grpc::ClientContext* context, const ::slm::GenerateRequest& request, ::grpc::CompletionQueue* cq) override;
    const ::grpc::internal::RpcMethod rpcmethod_generate_;
  };
  static std::unique_ptr<Stub> NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());

  class Service : public ::grpc::Service {
   public:
    Service();
    virtual ~Service();
    virtual ::grpc::Status generate(::grpc::ServerContext* context, const ::slm::GenerateRequest* request, ::slm::GenerateResponse* response);
  };
  template <class BaseClass>
  class WithAsyncMethod_generate : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_generate() {
      ::grpc::Service::MarkMethodAsync(0);
    }
    ~WithAsyncMethod_generate() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status generate(::grpc::ServerContext* /*context*/, const ::slm::GenerateRequest* /*request*/, ::slm::GenerateResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void Requestgenerate(::grpc::ServerContext* context, ::slm::GenerateRequest* request, ::grpc::ServerAsyncResponseWriter< ::slm::GenerateResponse>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  typedef WithAsyncMethod_generate<Service > AsyncService;
  template <class BaseClass>
  class WithCallbackMethod_generate : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_generate() {
      ::grpc::Service::MarkMethodCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::slm::GenerateRequest, ::slm::GenerateResponse>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::slm::GenerateRequest* request, ::slm::GenerateResponse* response) { return this->generate(context, request, response); }));}
    void SetMessageAllocatorFor_generate(
        ::grpc::MessageAllocator< ::slm::GenerateRequest, ::slm::GenerateResponse>* allocator) {
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(0);
      static_cast<::grpc::internal::CallbackUnaryHandler< ::slm::GenerateRequest, ::slm::GenerateResponse>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~WithCallbackMethod_generate() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status generate(::grpc::ServerContext* /*context*/, const ::slm::GenerateRequest* /*request*/, ::slm::GenerateResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* generate(
      ::grpc::CallbackServerContext* /*context*/, const ::slm::GenerateRequest* /*request*/, ::slm::GenerateResponse* /*response*/)  { return nullptr; }
  };
  typedef WithCallbackMethod_generate<Service > CallbackService;
  typedef CallbackService ExperimentalCallbackService;
  template <class BaseClass>
  class WithGenericMethod_generate : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_generate() {
      ::grpc::Service::MarkMethodGeneric(0);
    }
    ~WithGenericMethod_generate() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status generate(::grpc::ServerContext* /*context*/, const ::slm::GenerateRequest* /*request*/, ::slm::GenerateResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithRawMethod_generate : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_generate() {
      ::grpc::Service::MarkMethodRaw(0);
    }
    ~WithRawMethod_generate() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status generate(::grpc::ServerContext* /*context*/, const ::slm::GenerateRequest* /*request*/, ::slm::GenerateResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void Requestgenerate(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_generate : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_generate() {
      ::grpc::Service::MarkMethodRawCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->generate(context, request, response); }));
    }
    ~WithRawCallbackMethod_generate() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status generate(::grpc::ServerContext* /*context*/, const ::slm::GenerateRequest* /*request*/, ::slm::GenerateResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* generate(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_generate : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_generate() {
      ::grpc::Service::MarkMethodStreamed(0,
        new ::grpc::internal::StreamedUnaryHandler<
          ::slm::GenerateRequest, ::slm::GenerateResponse>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::slm::GenerateRequest, ::slm::GenerateResponse>* streamer) {
                       return this->Streamedgenerate(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_generate() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status generate(::grpc::ServerContext* /*context*/, const ::slm::GenerateRequest* /*request*/, ::slm::GenerateResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status Streamedgenerate(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::slm::GenerateRequest,::slm::GenerateResponse>* server_unary_streamer) = 0;
  };
  typedef WithStreamedUnaryMethod_generate<Service > StreamedUnaryService;
  typedef Service SplitStreamedService;
  typedef WithStreamedUnaryMethod_generate<Service > StreamedService;
};

}  // namespace slm


#include <grpcpp/ports_undef.inc>
#endif  // GRPC_slm_2eproto__INCLUDED
